name: 'Agent Code Review Feedback'
description: 'Aggregates PR review comments into a file and comment for AI coding assistants'
author: 'petitsamuel'

branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  feedback-file:
    description: 'Path to write the feedback file (set to empty to disable)'
    required: false
    default: '.github/REVIEW_FEEDBACK.md'
  post-comment:
    description: 'Whether to post/update a PR comment with the feedback'
    required: false
    default: 'true'
  include-resolved:
    description: 'Whether to include resolved comments (as checked items)'
    required: false
    default: 'true'

outputs:
  open-count:
    description: 'Number of open review comments'
  resolved-count:
    description: 'Number of resolved review comments'
  feedback-file:
    description: 'Path to the feedback file (if created)'

runs:
  using: 'node20'
  main: 'dist/index.js'
